### ISSUE TITLE
NetworkPolicies with both namespaceSelector and podSelector in a single from rule are not displayed correctly

### ISSUE THREAD

**Issue by alexisph** [runoncloud/kubectl-np-viewer#6]
Hello,

Thanks for this great plugin. I've noticed an issue where NetworkPolicies with both namespaceSelector and podSelector in a single from rule are not displayed correctly. Example:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-example
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ns1
      podSelector:
        matchLabels:
          app: app1
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ns2
      podSelector:
        matchLabels:
          app: app2
          version: v2
  policyTypes:
  - Ingress
```

which is shown as:

```sh
kubectl describe netpol allow-example -n default

Name:         allow-example
Namespace:    default
Created on:   2022-05-04 14:13:50 +0300 EEST
Labels:       <none>
Annotations:  <none>
Spec:
  PodSelector:     <none> (Allowing the specific traffic to all pods in this namespace)
  Allowing ingress traffic:
    To Port: <any> (traffic allowed to all ports)
    From:
      NamespaceSelector: kubernetes.io/metadata.name=ns1
      PodSelector: app=app1
    From:
      NamespaceSelector: kubernetes.io/metadata.name=ns2
      PodSelector: app=app2,version=v2
  Not affecting egress traffic
  Policy Types: Ingress
```

but np-viewer is displaying it like this:

```sh
kubectl np-viewer -n default

+----------------+---------+-----------+------+---------------------------------+---------------+----------+-------+
| NETWORK POLICY |  TYPE   | NAMESPACE | PODS |       NAMESPACES SELECTOR       | PODS SELECTOR | IP BLOCK | PORTS |
+----------------+---------+-----------+------+---------------------------------+---------------+----------+-------+
| allow-example  | Ingress |  default  |  *   |             default             |   app=app1    |    *     |   *   |
+----------------+---------+-----------+------+---------------------------------+---------------+----------+-------+
| allow-example  | Ingress |  default  |  *   | kubernetes.io/metadata.name=ns1 |       *       |    *     |   *   |
+----------------+---------+-----------+------+---------------------------------+---------------+----------+-------+
| allow-example  | Ingress |  default  |  *   |             default             |   app=app2    |    *     |   *   |
|                |         |           |      |                                 |  version=v2   |          |       |
+----------------+---------+-----------+------+---------------------------------+---------------+----------+-------+
| allow-example  | Ingress |  default  |  *   | kubernetes.io/metadata.name=ns2 |       *       |    *     |   *   |
+----------------+---------+-----------+------+---------------------------------+---------------+----------+-------+
```

which is wrong.
